# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CCSUDining' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CCSUDining

    pod 'Firebase/Core'
    pod 'CodableFirebase'
    pod 'Firebase/Firestore'
    pod 'Firebase/Database'
    pod 'Firebase/Auth'

  target 'CCSUDiningTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CCSUDiningUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
